"""add vps model

Revision ID: 3a68569e94ee
Revises: c7bd4d626442
Create Date: 2026-04-27 09:58:34.332192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a68569e94ee'
down_revision: Union[str, Sequence[str], None] = 'c7bd4d626442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vps_accounts', sa.Column('protocol', sa.String(length=8), nullable=True))
    op.add_column('vps_accounts', sa.Column('port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vps_accounts', 'port')
    op.drop_column('vps_accounts', 'protocol')
    # ### end Alembic commands ###
