"""Add new fields to TradingAccount

Revision ID: 75210dcbe1e1
Revises: 
Create Date: 2026-04-10 13:30:50.675966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75210dcbe1e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trading_accounts', sa.Column('manual_trades', sa.Boolean(), nullable=True))
    op.add_column('trading_accounts', sa.Column('use_dedicated_ip', sa.Boolean(), nullable=True))
    op.add_column('trading_accounts', sa.Column('magic', sa.Integer(), nullable=True))
    op.add_column('trading_accounts', sa.Column('connection_status', sa.String(length=20), nullable=True))
    op.add_column('trading_accounts', sa.Column('last_connected_at', sa.DateTime(), nullable=True))
    op.add_column('trading_accounts', sa.Column('last_error', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'trading_accounts', ['metaapi_account_id'])
    op.create_unique_constraint(None, 'trading_accounts', ['login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trading_accounts', type_='unique')
    op.drop_constraint(None, 'trading_accounts', type_='unique')
    op.drop_column('trading_accounts', 'last_error')
    op.drop_column('trading_accounts', 'last_connected_at')
    op.drop_column('trading_accounts', 'connection_status')
    op.drop_column('trading_accounts', 'magic')
    op.drop_column('trading_accounts', 'use_dedicated_ip')
    op.drop_column('trading_accounts', 'manual_trades')
    # ### end Alembic commands ###
