"""add listerner to model

Revision ID: 7fd59b6cca5c
Revises: 3a68569e94ee
Create Date: 2026-04-30 12:50:57.804180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fd59b6cca5c'
down_revision: Union[str, Sequence[str], None] = '3a68569e94ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trading_accounts', sa.Column('listener_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trading_accounts', 'listener_active')
    # ### end Alembic commands ###
