"""change status in account to state

Revision ID: 87015bfa63bd
Revises: 75210dcbe1e1
Create Date: 2026-04-12 07:24:33.231006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87015bfa63bd'
down_revision: Union[str, Sequence[str], None] = '75210dcbe1e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trading_accounts', sa.Column('state', sa.String(length=50), nullable=True))
    op.drop_column('trading_accounts', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trading_accounts', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('trading_accounts', 'state')
    # ### end Alembic commands ###
