"""add userid to copy settings

Revision ID: 8eb2ddb58273
Revises: 698f0f9a018d
Create Date: 2026-04-19 08:17:22.484714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb2ddb58273'
down_revision: Union[str, Sequence[str], None] = '698f0f9a018d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copy_trade_settings', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'copy_trade_settings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'copy_trade_settings', type_='foreignkey')
    op.drop_column('copy_trade_settings', 'user_id')
    # ### end Alembic commands ###
