"""add position tracker

Revision ID: b27df94b6e39
Revises: 2d021fb8d344
Create Date: 2026-05-14 11:28:06.400185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b27df94b6e39'
down_revision: Union[str, Sequence[str], None] = '2d021fb8d344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_account_id', sa.Integer(), nullable=False),
    sa.Column('master_ticket', sa.String(length=64), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('closed_by_tracker', sa.Boolean(), nullable=True),
    sa.Column('intervention_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['master_account_id'], ['trading_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_account_id', 'master_ticket', name='uniq_tracked_pos')
    )
    op.create_index(op.f('ix_tracked_positions_master_account_id'), 'tracked_positions', ['master_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracked_positions_master_account_id'), table_name='tracked_positions')
    op.drop_table('tracked_positions')
    # ### end Alembic commands ###
