"""add pips offset to copy settings

Revision ID: c673beb69775
Revises: 8eb2ddb58273
Create Date: 2026-04-19 09:12:34.487397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c673beb69775'
down_revision: Union[str, Sequence[str], None] = '8eb2ddb58273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copy_trade_settings', sa.Column('pips_offset_enabled', sa.Boolean(), nullable=True))
    op.add_column('copy_trade_settings', sa.Column('pips_offset', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('copy_trade_settings', 'pips_offset')
    op.drop_column('copy_trade_settings', 'pips_offset_enabled')
    # ### end Alembic commands ###
