"""add can use calculator to db

Revision ID: c7bd4d626442
Revises: e6bef491a34e
Create Date: 2026-04-24 11:08:56.004506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7bd4d626442'
down_revision: Union[str, Sequence[str], None] = 'e6bef491a34e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_permissions', sa.Column('can_use_calculator', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_permissions', 'can_use_calculator')
    # ### end Alembic commands ###
