"""add fx cycle calculator

Revision ID: e6bef491a34e
Revises: c673beb69775
Create Date: 2026-04-24 10:18:52.389689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6bef491a34e'
down_revision: Union[str, Sequence[str], None] = 'c673beb69775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('big_balance', sa.Float(), nullable=False),
    sa.Column('small_balance', sa.Float(), nullable=False),
    sa.Column('starting_pips', sa.Integer(), nullable=False),
    sa.Column('num_phases', sa.Integer(), nullable=False),
    sa.Column('trades_per_phase', sa.Integer(), nullable=False),
    sa.Column('losses', sa.JSON(), nullable=False),
    sa.Column('ea_name', sa.String(length=128), nullable=True),
    sa.Column('use_name_as_comment', sa.Boolean(), nullable=True),
    sa.Column('signal_tf', sa.String(length=16), nullable=True),
    sa.Column('ema_period', sa.Integer(), nullable=True),
    sa.Column('bb_period', sa.Integer(), nullable=True),
    sa.Column('bb_deviation', sa.Float(), nullable=True),
    sa.Column('require_closed_candle', sa.Boolean(), nullable=True),
    sa.Column('require_close_inside_bb', sa.Boolean(), nullable=True),
    sa.Column('cycle_state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_slots_user_id'), 'cycle_slots', ['user_id'], unique=False)
    op.create_table('cycle_phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('phase_num', sa.Integer(), nullable=False),
    sa.Column('recovery', sa.Float(), nullable=False),
    sa.Column('tp_value', sa.Float(), nullable=False),
    sa.Column('lot', sa.Float(), nullable=False),
    sa.Column('sl_base_pips', sa.Integer(), nullable=False),
    sa.Column('loss_real', sa.Float(), nullable=False),
    sa.Column('disallineamento', sa.Float(), nullable=False),
    sa.Column('trades', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['cycle_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_phases_slot_id'), 'cycle_phases', ['slot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cycle_phases_slot_id'), table_name='cycle_phases')
    op.drop_table('cycle_phases')
    op.drop_index(op.f('ix_cycle_slots_user_id'), table_name='cycle_slots')
    op.drop_table('cycle_slots')
    # ### end Alembic commands ###
